[package]
name = "server"
authors = ["Himadu2000 <49078336+Himadu2000@users.noreply.github.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
async-graphql = "7.0.6"
async-graphql-rocket = "7.0.6"
rocket = "0.5.1"
